openapi: 3.1.0
x-stoplight:
  id: g27g8q3gjuf7m
info:
  title: payreco
  version: '1.0'
  description: API for payreco app
  summary: 'OpenAPI documentation '
  contact:
    name: payreco
    url: 'http://localhost:3001/contact'
  license:
    name: MIT
    url: 'http://localhost:3001/license'
  termsOfService: 'http://localhost:3001/terms'
servers:
  - url: 'http://localhost:3000/api/v1'
paths:
  /user:
    parameters: []
    get:
      summary: Get a user
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                example-1:
                  value:
                    id: adffgg
                    uid: JYBfksjIBSDOjs
                    name: 田中
                    target_amount: 200000
                    created_at: '2019-08-24T14:15:22Z'
                    updated_at: '2019-08-24T14:15:22Z'
      operationId: get-users-userId
      description: Get a user
      tags:
        - Users
      parameters: []
    patch:
      summary: Update a use
      operationId: patch-users-userId
      responses:
        '200':
          description: ok
        '422':
          description: unprocessable entity
      description: Update a user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserParams'
            examples:
              example-1:
                value:
                  target_amount: 200000
        description: Patch user properties to update.
    delete:
      summary: Delete a user
      operationId: delete-users-userId
      responses:
        '204':
          description: no content
          content:
            application/json:
              schema:
                type: string
              examples:
                deleted user:
                  value: string
      description: Delete a user
  '/works/{work_id}':
    parameters:
      - schema:
          type: string
        name: work_id
        in: path
        required: true
        description: Work information
    delete:
      summary: Delete a work
      operationId: delete-works-work_id
      responses:
        '204':
          description: no content
          content:
            application/json:
              schema:
                type: string
              examples:
                deleted work:
                  value: string
      description: Delete a work
    patch:
      summary: Update a work
      operationId: patch-works-work_id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkParams'
            examples:
              example-1:
                value:
                  date: '2019-08-24'
                  starting_time: '2019-08-24T14:15:22Z'
                  ending_time: '2019-08-24T18:15:22Z'
                  break_time: 60
                  working_hours: 3
                  pay_amount: 45
                  memo: メモ
                  user_id: fsgskdj
                  company_id: ggsgrtt
      description: Update a work
      responses:
        '200':
          description: ok
        '422':
          description: unprocessable entity
  /works:
    get:
      summary: Get works
      tags:
        - Works
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                x-examples:
                  example-1:
                    - id: gdgdsgs
                      date: '2019-08-24'
                      starting_time: '2019-08-24T14:15:22Z'
                      ending_time: '2019-08-24T18:15:22Z'
                      break_time: 60
                      working_hours: 3
                      pay_amount: 45
                      memo: メモ
                      user_id: fsgskdj
                      company_id: ggsgrtt
                      created_at: '2019-08-24T14:15:22Z'
                      updated_at: '2019-08-24T14:15:22Z'
                items:
                  $ref: '#/components/schemas/Work'
              examples:
                example-1:
                  value:
                    - id: gdgdsgs
                      date: '2019-08-24'
                      starting_time: '2019-08-24T14:15:22Z'
                      ending_time: '2019-08-24T18:15:22Z'
                      break_time: 60
                      working_hours: 3
                      pay_amount: 45
                      memo: メモ
                      user_id: fsgskdj
                      company_id: ggsgrtt
                      created_at: '2019-08-24T14:15:22Z'
                      updated_at: '2019-08-24T14:15:22Z'
      operationId: get-works
      description: Get works
    post:
      summary: Create a work
      operationId: post-works
      responses:
        '201':
          description: created
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkParams'
              x-examples:
                example-1:
                  id: gdgdsgs
                  date: '2019-08-24'
                  starting_time: '2019-08-24T14:15:22Z'
                  ending_time: '2019-08-24T18:15:22Z'
                  break_time: 60
                  working_hours: 3
                  pay_amount: 45
                  memo: メモ
                  user_id: fsgskdj
                  company_id: ggsgrtt
                  created_at: '2019-08-24T14:15:22Z'
                  updated_at: '2019-08-24T14:15:22Z'
            examples:
              example-1:
                value:
                  date: '2019-08-24'
                  starting_time: '2019-08-24T14:15:22Z'
                  ending_time: '2019-08-24T18:15:22Z'
                  break_time: 60
                  working_hours: 3
                  pay_amount: 45
                  memo: メモ
                  user_id: fsgskdj
                  company_id: ggsgrtt
      description: Create a work
  /companies:
    get:
      summary: Get companies
      tags:
        - Companies
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company'
              examples:
                example-1:
                  value:
                    - id: ggsgrtt
                      name: 株式会社〇〇
                      hourly_wage_system: true
                      wage_amount: 15
                      currency_type: USD
                      user_id: dggghhs
                      deleted_at: null
                      created_at: '2019-08-24T14:15:22Z'
                      updated_at: '2019-08-24T14:15:22Z'
      operationId: get-companies
      description: Get companies information
    post:
      summary: Create a company
      operationId: post-companies
      responses:
        '201':
          description: created
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyParams'
            examples:
              example-1:
                value:
                  name: 株式会社××
                  hourly_wage_system: true
                  wage_amount: 0
                  currency_type: USD
      description: Create a company
  '/companies/{company_id}':
    parameters:
      - schema:
          type: string
        name: company_id
        in: path
        required: true
        description: Company information
    patch:
      summary: Update  a company
      operationId: patch-companies-company_id
      responses:
        '200':
          description: ok
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyParams'
            examples:
              example-1:
                value:
                  name: 株式会社〇〇
                  hourly_wage_system: true
                  wage_amount: 10
                  currency_type: USD
      description: Update a company
    delete:
      summary: Delete a company
      operationId: delete-companies-company_id
      responses:
        '204':
          description: no content
          content:
            application/json:
              schema:
                type: string
              examples:
                deleted company:
                  value: string
      description: Delete a company
  /exchange-rates:
    get:
      summary: Get exchange rates
      tags:
        - Exchange rates
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExchangeRate'
              examples:
                example-1:
                  value:
                    - id: 1
                      year_and_month: 202208
                      exchange_rate_list:
                        円: 1
                        米ドル: 0.007416
                        ユーロ: 0.007282
                        英ポンド: 0.006149
                        インドルピー: 0.5887
                        豪ドル: 0.01075
                        カナダドル: 0.009609
                        ランド: 0.124
                        NZドル: 0.01187
                        SGドル: 0.01022
                        人民元: 0.05024
                        スイスフラン: 0.007126
                      created_at: '2019-08-24T14:15:22Z'
                      updated_at: '2019-08-24T14:15:22Z'
      operationId: get-exchange-rates
      description: Get exchange rates
  /authentication:
    delete:
      summary: Delete an authentication
      operationId: delete-authentication
      responses:
        '204':
          description: No Content
      description: Delete an authentication
components:
  schemas:
    User:
      title: User
      type: object
      description: User model
      examples:
        - id: adffgg
          uid: JYBfksjIBSDOjs
          name: 田中
          target_amount: 200000
          created_at: '2019-08-24T14:15:22Z'
          updated_at: '2019-08-24T14:15:22Z'
      x-tags:
        - Users
      properties:
        id:
          type: string
          readOnly: true
        uid:
          type: string
          readOnly: true
        name:
          type: string
          readOnly: true
        target_amount:
          type:
            - number
            - 'null'
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
        - id
        - uid
        - name
        - target_amount
        - created_at
        - updated_at
    Company:
      title: Company
      x-stoplight:
        id: p20ujg3asx194
      type: object
      description: Company model
      x-tags:
        - Cpmpanies
      examples:
        - id: ggsgrtt
          name: 株式会社〇〇
          hourly_wage_system: true
          wage_amount: 15
          currency_type: USD
          user_id: dggghhs
          deleted_at: null
          created_at: '2019-08-24T14:15:22Z'
          updated_at: '2019-08-24T14:15:22Z'
      properties:
        id:
          type: string
          readOnly: true
        name:
          type: string
        hourly_wage_system:
          type: boolean
        wage_amount:
          type:
            - number
            - 'null'
          format: float
        currency_type:
          type: string
        user_id:
          type: string
          readOnly: true
        deleted_at:
          type:
            - string
            - 'null'
          format: date-time
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
        - id
        - name
        - hourly_wage_system
        - wage_amount
        - currency_type
        - user_id
        - deleted_at
        - created_at
        - updated_at
    Work:
      title: Work
      x-stoplight:
        id: hum3nwximkuo4
      type: object
      description: Work model
      examples:
        - id: gdgdsgs
          date: '2019-08-24'
          starting_time: '2019-08-24T14:15:22Z'
          ending_time: '2019-08-24T18:15:22Z'
          break_time: 60
          working_hours: 3
          pay_amount: 45
          memo: メモ
          user_id: fsgskdj
          company_id: ggsgrtt
          created_at: '2019-08-24T14:15:22Z'
          updated_at: '2019-08-24T14:15:22Z'
      x-tags:
        - Works
      properties:
        id:
          type: string
          readOnly: true
        date:
          type: string
          format: date
        starting_time:
          type:
            - string
            - 'null'
          format: date-time
        ending_time:
          type:
            - string
            - 'null'
          format: date-time
        break_time:
          type:
            - number
            - 'null'
        working_hours:
          type: number
          format: float
        pay_amount:
          type: number
          format: float
        memo:
          type:
            - string
            - 'null'
        user_id:
          type: string
          readOnly: true
        company_id:
          type: string
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
        - id
        - date
        - starting_time
        - ending_time
        - break_time
        - working_hours
        - pay_amount
        - memo
        - user_id
        - company_id
        - created_at
        - updated_at
    ExchangeRate:
      title: ExchangeRate
      x-stoplight:
        id: 9a4ilxb1olzzx
      type: object
      examples:
        - id: 1
          year_and_month: 202208
          exchange_rate_list:
            円: 1
            米ドル: 0.007416
            ユーロ: 0.007282
            英ポンド: 0.006149
            インドルピー: 0.5887
            豪ドル: 0.01075
            カナダドル: 0.009609
            ランド: 0.124
            NZドル: 0.01187
            SGドル: 0.01022
            人民元: 0.05024
            スイスフラン: 0.007126
          created_at: '2019-08-24T14:15:22Z'
          updated_at: '2019-08-24T14:15:22Z'
      properties:
        id:
          type: number
          readOnly: true
        year_and_month:
          type: number
        exchange_rate_list:
          type: object
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - year_and_month
        - exchange_rate_list
        - created_at
        - updated_at
    WorkParams:
      type: object
      x-examples:
        example-1:
          date: '2019-08-24'
          starting_time: '2019-08-24T14:15:22Z'
          ending_time: '2019-08-24T18:15:22Z'
          break_time: 60
          working_hours: 3
          pay_amount: 45
          memo: メモ
          user_id: fsgskdj
          company_id: ggsgrtt
      examples:
        - date: '2019-08-24'
          starting_time: '2019-08-24T14:15:22Z'
          ending_time: '2019-08-24T18:15:22Z'
          break_time: 60
          working_hours: 3
          pay_amount: 5000
          memo: メモ
          company_id: fskdfjd
      properties:
        date:
          type: string
          format: date
        starting_time:
          type:
            - string
            - 'null'
          format: date-time
        ending_time:
          type:
            - string
            - 'null'
          format: date-time
        break_time:
          type:
            - number
            - 'null'
        working_hours:
          type: number
          format: float
        pay_amount:
          type: number
          format: float
        memo:
          type:
            - string
            - 'null'
        company_id:
          type: string
      required:
        - date
        - starting_time
        - ending_time
        - break_time
        - working_hours
        - pay_amount
        - memo
        - company_id
      title: WorkParams
    CompanyParams:
      type: object
      x-examples:
        example-1:
          name: 株式会社〇〇
          hourly_wage_system: true
          wage_amount: 15
          currency_type: USD
          user_id: dggghhs
      examples:
        - name: 株式会社〇〇
          hourly_wage_system: true
          wage_amount: 10
          currency_type: USD
      properties:
        name:
          type: string
        hourly_wage_system:
          type: boolean
        wage_amount:
          type:
            - number
            - 'null'
          format: float
        currency_type:
          type: string
      required:
        - name
        - hourly_wage_system
        - wage_amount
        - currency_type
      title: CompanyParams
    UserParams:
      type: object
      x-examples:
        example-1:
          id: adffgg
          uid: JYBfksjIBSDOjs
          name: 田中
          target_amount: 200000
          created_at: '2019-08-24T14:15:22Z'
          updated_at: '2019-08-24T14:15:22Z'
      examples:
        - target_amount: 200000
      properties:
        target_amount:
          type:
            - number
            - 'null'
      required:
        - target_amount
      title: UserParams
  securitySchemes: {}
tags:
  - name: Companies
    description: Company model
  - name: Exchange rates
    description: Exchange rate model
  - name: Users
    description: User model
  - name: Works
    description: Work model
